//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopIM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Sl_ { get; set; }
        public virtual Product Product { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public int InventoryNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        
    }
}
